#!/usr/bin/env bash
set -euo pipefail

# Deploys a WireGuard + ConsolePi spoke on a fresh Debian (or Debian-based) machine,
# e.g. a laptop. Unlike SPOKE/deploy-spoke.sh (Raspberry Pi one-line installer), this
# script updates apt, installs required packages, and installs ConsolePi manually
# (git clone + venv), matching the non-Pi install method ConsolePi documents upstream.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${SCRIPT_DIR}/.env"
TIMESTAMP="$(date +%Y%m%d-%H%M%S)"
CONSOLEPI_HOME="/etc/ConsolePi"
CONSOLEPI_REPO_URL="${CONSOLEPI_REPO_URL:-https://github.com/Pack3tL0ss/ConsolePi.git}"
NEW_KEY_REQUESTED="false"
GET_KEY_REQUESTED="false"
RENDER_CONFIG_ONLY="false"
STATUS_ONLY="false"
SKIP_PACKAGES="false"
INSTALL_CONSOLEPI="${INSTALL_CONSOLEPI:-true}"
HUB_REMOTE_SSH_USER="${HUB_REMOTE_SSH_USER:-}"
HUB_REMOTE_SSH_PUBKEY="${HUB_REMOTE_SSH_PUBKEY:-}"
HUB_REMOTE_SSH_PUBKEY_FILE="${HUB_REMOTE_SSH_PUBKEY_FILE:-${SCRIPT_DIR}/hub_spoke_ed25519.pub}"
SUDO=""

is_valid_ipv4() {
  local ip="$1"
  local octet

  [[ "${ip}" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]] || return 1
  IFS='.' read -r -a octets <<< "${ip}"
  for octet in "${octets[@]}"; do
    ((octet >= 0 && octet <= 255)) || return 1
  done
}

derive_hub_ip_from_subnet() {
  local subnet="$1"
  local base_ip
  local prefix
  local o1
  local o2
  local o3
  local o4

  base_ip="${subnet%/*}"
  prefix="${subnet#*/}"

  if [[ "${prefix}" != "24" ]]; then
    echo "WG_SUBNET must be a /24 network: ${subnet}" >&2
    return 1
  fi

  is_valid_ipv4 "${base_ip}" || {
    echo "Invalid subnet base IP: ${base_ip}" >&2
    return 1
  }

  IFS='.' read -r o1 o2 o3 o4 <<< "${base_ip}"
  printf '%s.%s.%s.1' "${o1}" "${o2}" "${o3}"
}

derive_spoke_ip_from_subnet() {
  local subnet="$1"
  local spoke_index="$2"
  local base_ip
  local prefix
  local o1
  local o2
  local o3
  local o4
  local host_octet

  [[ "${spoke_index}" =~ ^[0-9]+$ ]] || {
    echo "WG_SPOKE must be a numeric slot index." >&2
    return 1
  }

  base_ip="${subnet%/*}"
  prefix="${subnet#*/}"

  if [[ "${prefix}" != "24" ]]; then
    echo "WG_SUBNET must be a /24 network: ${subnet}" >&2
    return 1
  fi

  is_valid_ipv4 "${base_ip}" || {
    echo "Invalid subnet base IP: ${base_ip}" >&2
    return 1
  }

  IFS='.' read -r o1 o2 o3 o4 <<< "${base_ip}"
  host_octet=$((10 + spoke_index))
  if ((host_octet < 11 || host_octet > 254)); then
    echo "Derived spoke host octet out of range for WG_SPOKE=${spoke_index}: ${host_octet}" >&2
    return 1
  fi

  printf '%s.%s.%s.%s' "${o1}" "${o2}" "${o3}" "${host_octet}"
}

derive_hub_port_from_profile() {
  local profile="$1"

  case "${profile}" in
    trusted)
      printf '51821'
      ;;
    untrusted)
      printf '51820'
      ;;
    *)
      echo "HUB_PROFILE must be 'trusted' or 'untrusted'" >&2
      return 1
      ;;
  esac
}

bool_is_true() {
  case "${1:-}" in
    true|TRUE|True|yes|YES|Yes|y|Y|1)
      return 0
      ;;
    false|FALSE|False|no|NO|No|n|N|0|"")
      return 1
      ;;
    *)
      echo "Invalid boolean value: ${1}" >&2
      return 2
      ;;
  esac
}

is_placeholder_value() {
  local value="$1"
  local placeholder="$2"

  [[ -z "${value}" || "${value}" == "${placeholder}" ]]
}

load_env_file() {
  if [[ ! -f "${ENV_FILE}" ]]; then
    echo "Missing ${ENV_FILE}. Copy .env.example to .env first." >&2
    return 1
  fi

  # shellcheck disable=SC1090
  source "${ENV_FILE}"
}

load_env_file_if_present() {
  if [[ -f "${ENV_FILE}" ]]; then
    # shellcheck disable=SC1090
    source "${ENV_FILE}"
  fi
}

persist_env_file() {
  if [[ -f "${ENV_FILE}" ]]; then
    cp "${ENV_FILE}" "${ENV_FILE}.bak.${TIMESTAMP}"
  fi

  cat > "${ENV_FILE}" <<EOF
# Generated by deploy-spoke-debian.sh on ${TIMESTAMP}
HUB_PROFILE=${HUB_PROFILE}
HUB_ENDPOINT=${HUB_ENDPOINT}
WG_SUBNET=${WG_SUBNET}
WG_SPOKE=${WG_SPOKE}
HUB_PUBLIC_KEY=${HUB_PUBLIC_KEY}
EOF

  printf 'HUB_REMOTE_SSH_USER=%q\n' "${HUB_REMOTE_SSH_USER}" >> "${ENV_FILE}"
}

is_valid_ssh_public_key() {
  local key="$1"

  [[ "${key}" =~ ^(ssh-ed25519|ssh-rsa|ecdsa-sha2-nistp(256|384|521))[[:space:]]+[A-Za-z0-9+/=]+([[:space:]].*)?$ ]]
}

resolve_hub_remote_ssh_pubkey() {
  local existing_key

  if [[ -f "${HUB_REMOTE_SSH_PUBKEY_FILE}" ]]; then
    if [[ -n "${HUB_REMOTE_SSH_PUBKEY}" ]]; then
      existing_key="$(awk 'NF {print; exit}' "${HUB_REMOTE_SSH_PUBKEY_FILE}")"
      if [[ -n "${existing_key}" && "${HUB_REMOTE_SSH_PUBKEY}" != "${existing_key}" ]]; then
        echo "Ignoring stale HUB_REMOTE_SSH_PUBKEY from env; using ${HUB_REMOTE_SSH_PUBKEY_FILE}."
      fi
    fi
    HUB_REMOTE_SSH_PUBKEY="$(awk 'NF {print; exit}' "${HUB_REMOTE_SSH_PUBKEY_FILE}")"
    return 0
  fi
}

ensure_hub_remote_ssh_access() {
  local target_user="$1"
  local target_key="$2"
  local target_home
  local target_auth_keys
  local target_group

  if ! id "${target_user}" >/dev/null 2>&1; then
    ${SUDO} useradd -m -s /bin/bash "${target_user}"
  else
    ${SUDO} usermod -s /bin/bash "${target_user}" >/dev/null 2>&1 || true
  fi

  target_group="$(${SUDO} id -gn "${target_user}")"
  target_home="$(${SUDO} getent passwd "${target_user}" | awk -F: '{print $6}')"
  [[ -n "${target_home}" ]] || target_home="/home/${target_user}"
  target_auth_keys="${target_home}/.ssh/authorized_keys"

  ${SUDO} install -d -m 700 -o "${target_user}" -g "${target_group}" "${target_home}/.ssh"
  ${SUDO} touch "${target_auth_keys}"
  ${SUDO} chown "${target_user}:${target_group}" "${target_auth_keys}"
  ${SUDO} chmod 600 "${target_auth_keys}"

  if ! ${SUDO} grep -Fqx "${target_key}" "${target_auth_keys}"; then
    printf '%s\n' "${target_key}" | ${SUDO} tee -a "${target_auth_keys}" >/dev/null
  fi

  if ! ${SUDO} grep -Fqx "${target_key}" "${target_auth_keys}"; then
    echo "Failed to install HUB remote SSH key for ${target_user}." >&2
    exit 1
  fi
}

ensure_wg_command() {
  if command -v wg >/dev/null 2>&1; then
    return 0
  fi

  echo "wireguard-tools is required for key generation and --get-key." >&2
  return 1
}

generate_spoke_private_key() {
  ensure_wg_command || return 1
  wg genkey
}

derive_public_key_from_private_key() {
  local private_key="$1"

  ensure_wg_command || return 1
  printf '%s' "${private_key}" | wg pubkey
}

resolve_private_key_from_state() {
  local private_key="${SPOKE_PRIVATE_KEY:-}"

  if ! is_placeholder_value "${private_key}" "CHANGE_ME_SPOKE_PRIVATE_KEY"; then
    printf '%s' "${private_key}"
    return 0
  fi

  if [[ -f "${SCRIPT_DIR}/rendered/spoke.privatekey" ]]; then
    awk 'NF { print; exit }' "${SCRIPT_DIR}/rendered/spoke.privatekey"
    return 0
  fi

  if [[ -f "/etc/wireguard/wg0.privatekey" ]]; then
    awk 'NF { print; exit }' "/etc/wireguard/wg0.privatekey"
    return 0
  fi

  echo "No existing spoke private key found." >&2
  return 1
}

print_current_spoke_public_key() {
  local private_key
  local public_key

  load_env_file_if_present
  private_key="$(resolve_private_key_from_state)"
  public_key="$(derive_public_key_from_private_key "${private_key}")"
  echo "Current spoke public key: ${public_key}"
}

render_config_from_env() {
  load_env_file || return 1

  local wg_profile
  local wg_subnet
  local wg_spoke
  local hub_port
  local hub_tunnel_ip
  local spoke_tunnel_ip
  local spoke_profile_label
  local spoke_private_key

  wg_profile="${HUB_PROFILE:-}"
  wg_subnet="${WG_SUBNET:-}"
  wg_spoke="${WG_SPOKE:-}"
  spoke_private_key="${SPOKE_PRIVATE_KEY:-}"

  : "${wg_profile:?HUB_PROFILE must be set}"
  : "${wg_subnet:?WG_SUBNET must be set}"
  : "${wg_spoke:?WG_SPOKE must be set}"
  : "${HUB_ENDPOINT:?HUB_ENDPOINT must be set}"
  : "${HUB_PUBLIC_KEY:?HUB_PUBLIC_KEY must be set}"
  PERSISTENT_KEEPALIVE="${PERSISTENT_KEEPALIVE:-25}"

  if is_placeholder_value "${spoke_private_key}" "CHANGE_ME_SPOKE_PRIVATE_KEY"; then
    spoke_private_key="$(resolve_private_key_from_state 2>/dev/null || true)"
  fi

  if [[ -z "${spoke_private_key}" ]]; then
    echo "No spoke private key available. Run full deploy to generate it, or use --new-key." >&2
    return 1
  fi

  if is_placeholder_value "${HUB_PUBLIC_KEY}" "CHANGE_ME_HUB_PUBLIC_KEY"; then
    echo "HUB_PUBLIC_KEY must be set to a real HUB public key." >&2
    return 1
  fi

  case "${wg_profile}" in
    trusted|untrusted)
      ;;
    *)
      echo "HUB_PROFILE must be 'trusted' or 'untrusted'" >&2
      return 1
      ;;
  esac

  hub_port="$(derive_hub_port_from_profile "${wg_profile}")"
  hub_tunnel_ip="$(derive_hub_ip_from_subnet "${wg_subnet}")"
  spoke_tunnel_ip="$(derive_spoke_ip_from_subnet "${wg_subnet}" "${wg_spoke}")"
  spoke_profile_label="$(printf '%s' "${wg_profile}" | tr '[:lower:]' '[:upper:]')"

  mkdir -p "${SCRIPT_DIR}/profiles" "${SCRIPT_DIR}/rendered"

  cat > "${SCRIPT_DIR}/profiles/wg0.conf.example" <<EOF
# ${spoke_profile_label} spoke template

[Interface]
Address = ${spoke_tunnel_ip}/32
PrivateKey = ${spoke_private_key}

[Peer]
PublicKey = ${HUB_PUBLIC_KEY}
Endpoint = ${HUB_ENDPOINT}:${hub_port}
AllowedIPs = ${hub_tunnel_ip}/32
PersistentKeepalive = ${PERSISTENT_KEEPALIVE}
EOF

  cp "${SCRIPT_DIR}/profiles/wg0.conf.example" "${SCRIPT_DIR}/rendered/wg0.conf"

  cat > "${SCRIPT_DIR}/rendered/summary.txt" <<EOF
  Rendered spoke profile: ${wg_profile}
  WG subnet: ${wg_subnet}
  Spoke slot: ${wg_spoke}
  Spoke address: ${spoke_tunnel_ip}/32
  Hub endpoint: ${HUB_ENDPOINT}:${hub_port}
  AllowedIPs: ${hub_tunnel_ip}/32
Output config: ${SCRIPT_DIR}/rendered/wg0.conf
EOF

  echo "Rendered ${wg_profile} spoke config at ${SCRIPT_DIR}/rendered/wg0.conf"
}

prompt_required() {
  local label="$1"
  local default_value="${2:-}"
  local reply

  while true; do
    if [[ -n "${default_value}" ]]; then
      read -r -p "${label} [${default_value}]: " reply
      reply="${reply:-${default_value}}"
    else
      read -r -p "${label}: " reply
    fi

    if [[ -n "${reply}" ]]; then
      printf '%s\n' "${reply}"
      return 0
    fi

    echo "A value is required."
  done
}

validate_port() {
  local port="$1"

  [[ "${port}" =~ ^[0-9]+$ ]] || return 1
  ((port >= 1 && port <= 65535))
}

prompt_port() {
  local label="$1"
  local default_value="$2"
  local reply

  while true; do
    reply="$(prompt_required "${label}" "${default_value}")"
    if validate_port "${reply}"; then
      printf '%s' "${reply}"
      return 0
    fi
    echo "Enter a valid port number."
  done
}

install_packages() {
  if [[ "${SKIP_PACKAGES}" == "true" ]]; then
    echo "Skipping apt update/install (--skip-packages)."
    return 0
  fi

  echo "Updating apt package index and upgrading installed packages..."
  ${SUDO} apt-get update
  ${SUDO} apt-get -y upgrade

  echo "Installing required packages..."
  ${SUDO} apt-get install -y \
    wireguard \
    wireguard-tools \
    git \
    python3 \
    python3-venv \
    python3-pip \
    python3-dev \
    build-essential \
    libffi-dev \
    libssl-dev \
    openssh-client \
    openssh-server \
    sudo \
    curl \
    ca-certificates \
    iproute2 \
    net-tools \
    iputils-ping

  ${SUDO} systemctl enable --now ssh >/dev/null 2>&1 || true
}

install_consolepi_debian() {
  if [[ -d "${CONSOLEPI_HOME}/.git" ]]; then
    echo "ConsolePi already present at ${CONSOLEPI_HOME}; pulling latest changes."
    ${SUDO} git -C "${CONSOLEPI_HOME}" pull
  else
    ${SUDO} git clone "${CONSOLEPI_REPO_URL}" "${CONSOLEPI_HOME}"
  fi

  if [[ ! -d "${CONSOLEPI_HOME}/venv" ]]; then
    ${SUDO} python3 -m venv "${CONSOLEPI_HOME}/venv"
  fi

  ${SUDO} "${CONSOLEPI_HOME}/venv/bin/pip" install --upgrade pip
  ${SUDO} "${CONSOLEPI_HOME}/venv/bin/pip" install --prefer-binary --upgrade -r "${CONSOLEPI_HOME}/installer/requirements.txt"

  ${SUDO} install -m 644 "${CONSOLEPI_HOME}/src/consolepi.sh" /etc/profile.d/consolepi.sh

  if [[ ! -f "${CONSOLEPI_HOME}/ConsolePi.yaml" ]]; then
    ${SUDO} cp "${CONSOLEPI_HOME}/ConsolePi.yaml.example" "${CONSOLEPI_HOME}/ConsolePi.yaml"
  fi

  if ! id consolepi >/dev/null 2>&1; then
    ${SUDO} useradd -m -s /bin/bash consolepi
  fi
}

configure_consolepi_yaml_defaults() {
  local yaml_file="${CONSOLEPI_HOME}/ConsolePi.yaml"
  [[ -f "${yaml_file}" ]] || return 0

  # Laptop/Debian spoke role: never advertise via cloud sync, only pull remote data.
  ${SUDO} sed -i \
    -e 's/^\( *cloud:\).*/\1 false/' \
    -e 's/^\( *cloud_pull_only:\).*/\1 true/' \
    "${yaml_file}"
}

enable_consolepi_api_service() {
  if ! command -v systemctl >/dev/null 2>&1; then
    echo "systemctl not available; start the ConsolePi API manually if needed."
    return 0
  fi

  local unit_src="${CONSOLEPI_HOME}/src/systemd/consolepi-api.service"

  if [[ -f "${unit_src}" ]]; then
    ${SUDO} cp "${unit_src}" /etc/systemd/system/consolepi-api.service
    ${SUDO} systemctl daemon-reload
    ${SUDO} systemctl enable --now consolepi-api
    echo "consolepi-api service enabled."
  else
    echo "WARNING: ${unit_src} not found; consolepi-api was not enabled." >&2
    echo "The HUB needs this API reachable on TCP 5000 over the tunnel; start it manually if required." >&2
  fi
}

harden_consolepi_account() {
  local nologin_shell=""

  if ! id consolepi >/dev/null 2>&1; then
    return 0
  fi

  # Shared HUB->SPOKE auth mode uses consolepi for non-interactive key-based access.
  # Keep this account login-capable in that mode.
  if [[ "${HUB_REMOTE_SSH_USER:-}" == "consolepi" ]]; then
    if command -v passwd >/dev/null 2>&1; then
      ${SUDO} passwd -u consolepi >/dev/null 2>&1 || true
    fi
    ${SUDO} usermod -s /bin/bash consolepi >/dev/null 2>&1 || true
    echo "ConsolePi account kept unlocked for shared HUB->SPOKE SSH access."
    return 0
  fi

  if command -v passwd >/dev/null 2>&1; then
    ${SUDO} passwd -l consolepi >/dev/null 2>&1 || true
  fi

  nologin_shell="$(command -v nologin 2>/dev/null || true)"
  if [[ -n "${nologin_shell}" ]]; then
    ${SUDO} usermod -s "${nologin_shell}" consolepi >/dev/null 2>&1 || true
  fi

  echo "ConsolePi account hardened: password locked${nologin_shell:+, shell set to nologin}."
}

print_runtime_status() {
  local wg_output

  echo
  echo "Runtime status:"

  if wg_output="$(wg show wg0 2>&1)"; then
    echo "  tunnel status: up (wg0 active)"
    echo "  wg show wg0:"
    while IFS= read -r line; do
      echo "    ${line}"
    done <<< "${wg_output}"
  else
    echo "  tunnel status: down (wg0 not active)"
    echo "  wg show wg0 error: ${wg_output}"
  fi

  if command -v systemctl >/dev/null 2>&1; then
    if systemctl is-active --quiet consolepi-api; then
      if command -v curl >/dev/null 2>&1 && curl -fsS --max-time 3 http://127.0.0.1:5000/api/v1.0/details >/dev/null 2>&1; then
        echo "  API status:    up (consolepi-api active and reachable)"
      else
        echo "  API status:    down (service active but endpoint unreachable)"
      fi
    else
      echo "  API status:    down (consolepi-api service inactive)"
    fi
  else
    echo "  API status:    unknown (systemctl not available)"
  fi
}

print_deployment_summary() {
  local hub_port
  local hub_tunnel_ip
  local spoke_tunnel_ip

  hub_port="$(derive_hub_port_from_profile "${HUB_PROFILE}")"
  hub_tunnel_ip="$(derive_hub_ip_from_subnet "${WG_SUBNET}")"
  spoke_tunnel_ip="$(derive_spoke_ip_from_subnet "${WG_SUBNET}" "${WG_SPOKE}")"

  echo "Deployment summary:"
  echo "Profile: ${HUB_PROFILE}"
  echo "Spoke slot: ${WG_SPOKE}"
  echo "Spoke tunnel address: ${spoke_tunnel_ip}/32"
  echo "Hub endpoint: ${HUB_ENDPOINT}:${hub_port}"
  echo "Hub tunnel address: ${hub_tunnel_ip}/32"
  echo "Persistent keepalive: ${PERSISTENT_KEEPALIVE}"
  echo "WireGuard config: /etc/wireguard/wg0.conf"
  echo "Spoke public key: ${SPOKE_PUBLIC_KEY}"
  echo "Spoke private key file: ${SPOKE_PRIVATE_KEY_FILE}"
  echo "Spoke public key file: ${SPOKE_PUBLIC_KEY_FILE}"
  echo "Remote SSH user for HUB access: ${HUB_REMOTE_SSH_USER}"

  if [[ "${INSTALL_CONSOLEPI}" == "true" ]]; then
    echo "ConsolePi install path: ${CONSOLEPI_HOME}"
    echo "ConsolePi venv: ${CONSOLEPI_HOME}/venv"
    echo "ConsolePi config: ${CONSOLEPI_HOME}/ConsolePi.yaml"
    echo "ConsolePi update: git -C ${CONSOLEPI_HOME} pull, or consolepi-sync if available"
  fi

  echo "Rendered summary: ${SCRIPT_DIR}/rendered/summary.txt"
  echo "ConsolePi API check: curl -s http://127.0.0.1:5000/api/v1.0/details | head"
  echo
  echo "Next check: ${SUDO} wg show"
  print_runtime_status
}

usage() {
  cat <<EOF
Usage: ./deploy-spoke-debian.sh [options]

Options:
  --new-key        Force generation of a new spoke private key
  --get-key        Print the current spoke public key and exit
  --render-config  Render spoke config from .env only (no install/apply)
  --status         Print live tunnel/API status and exit
  --skip-packages  Skip apt update/upgrade/install (assumes packages already present)
  --no-consolepi   Skip ConsolePi install (WireGuard tunnel only)
  --help           Show this help
EOF
}

for arg in "$@"; do
  case "$arg" in
    --new-key)
      NEW_KEY_REQUESTED="true"
      ;;
    --get-key)
      GET_KEY_REQUESTED="true"
      ;;
    --render-config)
      RENDER_CONFIG_ONLY="true"
      ;;
    --status)
      STATUS_ONLY="true"
      ;;
    --skip-packages)
      SKIP_PACKAGES="true"
      ;;
    --no-consolepi)
      INSTALL_CONSOLEPI="false"
      ;;
    --help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: ${arg}" >&2
      usage >&2
      exit 1
      ;;
  esac
done

echo "ConnectPi Debian spoke installer"
echo

if [[ "${GET_KEY_REQUESTED}" == "true" ]]; then
  print_current_spoke_public_key
  exit 0
fi

if [[ "${RENDER_CONFIG_ONLY}" == "true" ]]; then
  render_config_from_env
  exit 0
fi

if [[ "${STATUS_ONLY}" == "true" ]]; then
  print_runtime_status
  exit 0
fi

if [[ ${EUID} -ne 0 ]]; then
  if command -v sudo >/dev/null 2>&1; then
    SUDO="sudo"
  else
    echo "Run as root or install sudo." >&2
    exit 1
  fi
fi

load_env_file_if_present

if [[ -z "${HUB_PROFILE:-}" ]]; then
  while true; do
    HUB_PROFILE="$(prompt_required "HUB profile (trusted/untrusted)" "untrusted")"
    case "${HUB_PROFILE}" in
      trusted|untrusted)
        break
        ;;
      *)
        echo "HUB_PROFILE must be trusted or untrusted."
        ;;
    esac
  done
fi

if [[ -z "${WG_SUBNET:-}" ]]; then
  if [[ "${HUB_PROFILE}" == "trusted" ]]; then
    WG_SUBNET="$(prompt_required "WireGuard subnet for this profile" "10.99.99.0/24")"
  else
    WG_SUBNET="$(prompt_required "WireGuard subnet for this profile" "10.99.98.0/24")"
  fi
fi

if [[ -z "${WG_SPOKE:-}" ]]; then
  WG_SPOKE="$(prompt_port "Spoke slot index" "1")"
fi

if [[ -z "${HUB_ENDPOINT:-}" ]]; then
  HUB_ENDPOINT="$(prompt_required "Hub endpoint hostname or public IP" "change-me.example.com")"
fi

if is_placeholder_value "${HUB_PUBLIC_KEY:-}" "CHANGE_ME_HUB_PUBLIC_KEY"; then
  HUB_PUBLIC_KEY="$(prompt_required "Hub public key")"
fi

PERSISTENT_KEEPALIVE="${PERSISTENT_KEEPALIVE:-25}"

if bool_is_true "${INSTALL_CONSOLEPI}"; then
  INSTALL_CONSOLEPI="true"
else
  INSTALL_CONSOLEPI="false"
fi

if is_placeholder_value "${HUB_PUBLIC_KEY}" "CHANGE_ME_HUB_PUBLIC_KEY"; then
  echo "HUB_PUBLIC_KEY must be set to a real HUB public key in ${ENV_FILE}." >&2
  exit 1
fi

HUB_REMOTE_SSH_USER="consolepi"
resolve_hub_remote_ssh_pubkey

if [[ -z "${HUB_REMOTE_SSH_PUBKEY}" ]]; then
  echo "HUB remote SSH public key is required for passwordless HUB->SPOKE access." >&2
  echo "Set HUB_REMOTE_SSH_PUBKEY, or place the key in ${HUB_REMOTE_SSH_PUBKEY_FILE}." >&2
  exit 1
fi

if ! is_valid_ssh_public_key "${HUB_REMOTE_SSH_PUBKEY}"; then
  echo "Invalid HUB_REMOTE_SSH_PUBKEY format." >&2
  echo "Expected a full key line, e.g. ssh-ed25519 AAAA..." >&2
  exit 1
fi

install_packages

if [[ "${NEW_KEY_REQUESTED}" == "true" ]]; then
  SPOKE_PRIVATE_KEY="$(generate_spoke_private_key)"
  echo "Generated spoke private key."
else
  if is_placeholder_value "${SPOKE_PRIVATE_KEY:-}" "CHANGE_ME_SPOKE_PRIVATE_KEY"; then
    SPOKE_PRIVATE_KEY="$(resolve_private_key_from_state 2>/dev/null || true)"
  fi

  if [[ -z "${SPOKE_PRIVATE_KEY:-}" ]]; then
    SPOKE_PRIVATE_KEY="$(generate_spoke_private_key)"
    echo "Generated spoke private key."
  fi
fi

SPOKE_PUBLIC_KEY="$(derive_public_key_from_private_key "${SPOKE_PRIVATE_KEY}")"

mkdir -p "${SCRIPT_DIR}/rendered"
SPOKE_PRIVATE_KEY_FILE="${SCRIPT_DIR}/rendered/spoke.privatekey"
SPOKE_PUBLIC_KEY_FILE="${SCRIPT_DIR}/rendered/spoke.publickey"
printf '%s\n' "${SPOKE_PRIVATE_KEY}" > "${SPOKE_PRIVATE_KEY_FILE}"
printf '%s\n' "${SPOKE_PUBLIC_KEY}" > "${SPOKE_PUBLIC_KEY_FILE}"
chmod 600 "${SPOKE_PRIVATE_KEY_FILE}" "${SPOKE_PUBLIC_KEY_FILE}"

if [[ "${NEW_KEY_REQUESTED}" == "true" ]]; then
  echo "Rotated spoke keypair via --new-key."
  echo "Spoke public key: ${SPOKE_PUBLIC_KEY}"
  echo "Store this on the HUB for the matching peer slot."
fi

persist_env_file
render_config_from_env

${SUDO} mkdir -p /etc/wireguard
if [[ -f /etc/wireguard/wg0.conf ]]; then
  ${SUDO} cp /etc/wireguard/wg0.conf "/etc/wireguard/wg0.conf.bak.${TIMESTAMP}"
fi
${SUDO} cp "${SCRIPT_DIR}/rendered/wg0.conf" /etc/wireguard/wg0.conf
${SUDO} cp "${SPOKE_PRIVATE_KEY_FILE}" /etc/wireguard/wg0.privatekey
${SUDO} cp "${SPOKE_PUBLIC_KEY_FILE}" /etc/wireguard/wg0.publickey
${SUDO} chmod 600 /etc/wireguard/wg0.conf
${SUDO} chmod 600 /etc/wireguard/wg0.privatekey /etc/wireguard/wg0.publickey

${SUDO} systemctl enable wg-quick@wg0
if ${SUDO} systemctl is-active --quiet wg-quick@wg0; then
  ${SUDO} systemctl restart wg-quick@wg0
else
  ${SUDO} systemctl start wg-quick@wg0
fi

if [[ "${INSTALL_CONSOLEPI}" == "true" ]]; then
  install_consolepi_debian
  configure_consolepi_yaml_defaults
  enable_consolepi_api_service
fi

harden_consolepi_account
ensure_hub_remote_ssh_access "${HUB_REMOTE_SSH_USER}" "${HUB_REMOTE_SSH_PUBKEY}"

echo
echo "Install complete."
print_deployment_summary
