#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${SCRIPT_DIR}/.env"
TIMESTAMP="$(date +%Y%m%d-%H%M%S)"
REPO_URL="${CONSOLEPI_HUB_REPO_URL:-https://github.com/LoveSkylark/ConsolePi-Hub}"
REPO_REF="${CONSOLEPI_HUB_REPO_REF:-main}"
RAW_BASE="${REPO_URL/github.com/raw.githubusercontent.com}/${REPO_REF}"
NEW_KEY_REQUESTED="false"
GET_KEY_REQUESTED="false"
RENDER_CONFIG_ONLY="false"
STATUS_ONLY="false"
CONSOLEPI_PRESEED_DIR="${SCRIPT_DIR}/consolepi-stage"
CONSOLEPI_PRESEED_FILE="${CONSOLEPI_PRESEED_DIR}/install.conf"
CONSOLEPI_PASSWORD=""
PRESEED_REMOVED="false"
KEEP_PRESEED="false"
HUB_REMOTE_SSH_USER="${HUB_REMOTE_SSH_USER:-}"
HUB_REMOTE_SSH_PUBKEY="${HUB_REMOTE_SSH_PUBKEY:-}"

is_valid_ipv4() {
  local ip="$1"
  local octet

  [[ "${ip}" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]] || return 1
  IFS='.' read -r -a octets <<< "${ip}"
  for octet in "${octets[@]}"; do
    ((octet >= 0 && octet <= 255)) || return 1
  done
}

derive_hub_ip_from_subnet() {
  local subnet="$1"
  local base_ip
  local prefix
  local o1
  local o2
  local o3
  local o4

  base_ip="${subnet%/*}"
  prefix="${subnet#*/}"

  if [[ "${prefix}" != "24" ]]; then
    echo "WG_SUBNET must be a /24 network: ${subnet}" >&2
    return 1
  fi

  is_valid_ipv4 "${base_ip}" || {
    echo "Invalid subnet base IP: ${base_ip}" >&2
    return 1
  }

  IFS='.' read -r o1 o2 o3 o4 <<< "${base_ip}"
  printf '%s.%s.%s.1' "${o1}" "${o2}" "${o3}"
}

derive_spoke_ip_from_subnet() {
  local subnet="$1"
  local spoke_index="$2"
  local base_ip
  local prefix
  local o1
  local o2
  local o3
  local o4
  local host_octet

  [[ "${spoke_index}" =~ ^[0-9]+$ ]] || {
    echo "WG_SPOKE must be a numeric slot index." >&2
    return 1
  }

  base_ip="${subnet%/*}"
  prefix="${subnet#*/}"

  if [[ "${prefix}" != "24" ]]; then
    echo "WG_SUBNET must be a /24 network: ${subnet}" >&2
    return 1
  fi

  is_valid_ipv4 "${base_ip}" || {
    echo "Invalid subnet base IP: ${base_ip}" >&2
    return 1
  }

  IFS='.' read -r o1 o2 o3 o4 <<< "${base_ip}"
  host_octet=$((10 + spoke_index))
  if ((host_octet < 11 || host_octet > 254)); then
    echo "Derived spoke host octet out of range for WG_SPOKE=${spoke_index}: ${host_octet}" >&2
    return 1
  fi

  printf '%s.%s.%s.%s' "${o1}" "${o2}" "${o3}" "${host_octet}"
}

derive_hub_port_from_profile() {
  local profile="$1"

  case "${profile}" in
    trusted)
      printf '51821'
      ;;
    untrusted)
      printf '51820'
      ;;
    *)
      echo "HUB_PROFILE must be 'trusted' or 'untrusted'" >&2
      return 1
      ;;
  esac
}

bool_is_true() {
  case "${1:-}" in
    true|TRUE|True|yes|YES|Yes|y|Y|1)
      return 0
      ;;
    false|FALSE|False|no|NO|No|n|N|0|"")
      return 1
      ;;
    *)
      echo "Invalid boolean value: ${1}" >&2
      return 2
      ;;
  esac
}

is_placeholder_value() {
  local value="$1"
  local placeholder="$2"

  [[ -z "${value}" || "${value}" == "${placeholder}" ]]
}

load_env_file() {
  if [[ ! -f "${ENV_FILE}" ]]; then
    echo "Missing ${ENV_FILE}. Copy .env.example to .env first." >&2
    return 1
  fi

  # shellcheck disable=SC1090
  source "${ENV_FILE}"
}

load_env_file_if_present() {
  if [[ -f "${ENV_FILE}" ]]; then
    # shellcheck disable=SC1090
    source "${ENV_FILE}"
  fi
}

normalize_country() {
  local country="$1"

  [[ "${country}" =~ ^[A-Za-z]{2}$ ]] || {
    echo "COUNTRY must be a two-letter code such as US or GB." >&2
    return 1
  }

  printf '%s' "${country^^}"
}

extract_country_from_locale_value() {
  local locale_value="$1"

  [[ "${locale_value}" =~ ^[A-Za-z]+_([A-Za-z]{2})(\.|@|$) ]] || return 1
  printf '%s' "${BASH_REMATCH[1]^^}"
}

derive_default_country() {
  local locale_value
  local derived_country

  for locale_value in "${LC_ALL:-}" "${LANG:-}"; do
    if [[ -n "${locale_value}" ]] && derived_country="$(extract_country_from_locale_value "${locale_value}" 2>/dev/null)"; then
      printf '%s' "${derived_country}"
      return 0
    fi
  done

  if [[ -r /etc/default/locale ]]; then
    locale_value="$(awk -F= '/^(LANG|LC_ALL)=/ { gsub(/"/, "", $2); print $2; exit }' /etc/default/locale)"
    if [[ -n "${locale_value}" ]] && derived_country="$(extract_country_from_locale_value "${locale_value}" 2>/dev/null)"; then
      printf '%s' "${derived_country}"
      return 0
    fi
  fi

  printf 'US'
}

resolve_country_code() {
  local configured_country="${COUNTRY:-}"

  if [[ -n "${configured_country}" ]]; then
    normalize_country "${configured_country}"
    return 0
  fi

  derive_default_country
}

persist_env_file() {
  if [[ -f "${ENV_FILE}" ]]; then
    cp "${ENV_FILE}" "${ENV_FILE}.bak.${TIMESTAMP}"
  fi

  cat > "${ENV_FILE}" <<EOF
# Generated by deploy-spoke.sh on ${TIMESTAMP}
HUB_PROFILE=${HUB_PROFILE}
HUB_ENDPOINT=${HUB_ENDPOINT}
WG_SUBNET=${WG_SUBNET}
WG_SPOKE=${WG_SPOKE}
HUB_PUBLIC_KEY=${HUB_PUBLIC_KEY}
EOF

  printf 'HUB_REMOTE_SSH_USER=%q\n' "${HUB_REMOTE_SSH_USER}" >> "${ENV_FILE}"
  printf 'HUB_REMOTE_SSH_PUBKEY=%q\n' "${HUB_REMOTE_SSH_PUBKEY}" >> "${ENV_FILE}"
}

is_valid_ssh_public_key() {
  local key="$1"

  [[ "${key}" =~ ^(ssh-ed25519|ssh-rsa|ecdsa-sha2-nistp(256|384|521))[[:space:]]+[A-Za-z0-9+/=]+([[:space:]].*)?$ ]]
}

resolve_default_remote_ssh_user() {
  if [[ -n "${SUDO_USER:-}" && "${SUDO_USER}" != "root" ]]; then
    printf '%s' "${SUDO_USER}"
    return 0
  fi

  if [[ -n "${USER:-}" && "${USER}" != "root" ]]; then
    printf '%s' "${USER}"
    return 0
  fi

  printf '%s' "consolepi"
}

ensure_hub_remote_ssh_access() {
  local target_user="$1"
  local target_key="$2"
  local target_home
  local target_auth_keys

  if ! id "${target_user}" >/dev/null 2>&1; then
    ${SUDO} useradd -m -s /bin/bash "${target_user}"
  fi

  target_home="$(${SUDO} getent passwd "${target_user}" | awk -F: '{print $6}')"
  [[ -n "${target_home}" ]] || target_home="/home/${target_user}"
  target_auth_keys="${target_home}/.ssh/authorized_keys"

  ${SUDO} install -d -m 700 -o "${target_user}" -g "${target_user}" "${target_home}/.ssh"
  ${SUDO} touch "${target_auth_keys}"
  ${SUDO} chown "${target_user}:${target_user}" "${target_auth_keys}"
  ${SUDO} chmod 600 "${target_auth_keys}"

  if ! ${SUDO} grep -Fqx "${target_key}" "${target_auth_keys}"; then
    printf '%s\n' "${target_key}" | ${SUDO} tee -a "${target_auth_keys}" >/dev/null
  fi
}

ensure_wg_command() {
  if command -v wg >/dev/null 2>&1; then
    return 0
  fi

  echo "wireguard-tools is required for key generation and --get-key." >&2
  return 1
}

generate_spoke_private_key() {
  ensure_wg_command || return 1
  wg genkey
}

derive_public_key_from_private_key() {
  local private_key="$1"

  ensure_wg_command || return 1
  printf '%s' "${private_key}" | wg pubkey
}

resolve_private_key_from_state() {
  local private_key="${SPOKE_PRIVATE_KEY:-}"

  if ! is_placeholder_value "${private_key}" "CHANGE_ME_SPOKE_PRIVATE_KEY"; then
    printf '%s' "${private_key}"
    return 0
  fi

  if [[ -f "${SCRIPT_DIR}/rendered/spoke.privatekey" ]]; then
    awk 'NF { print; exit }' "${SCRIPT_DIR}/rendered/spoke.privatekey"
    return 0
  fi

  if [[ -f "/etc/wireguard/wg0.privatekey" ]]; then
    awk 'NF { print; exit }' "/etc/wireguard/wg0.privatekey"
    return 0
  fi

  echo "No existing spoke private key found." >&2
  return 1
}

print_current_spoke_public_key() {
  local private_key
  local public_key

  load_env_file_if_present
  private_key="$(resolve_private_key_from_state)"
  public_key="$(derive_public_key_from_private_key "${private_key}")"
  echo "Current spoke public key: ${public_key}"
}

print_deployment_summary() {
  local hub_port
  local hub_tunnel_ip
  local spoke_tunnel_ip

  hub_port="$(derive_hub_port_from_profile "${HUB_PROFILE}")"
  hub_tunnel_ip="$(derive_hub_ip_from_subnet "${WG_SUBNET}")"
  spoke_tunnel_ip="$(derive_spoke_ip_from_subnet "${WG_SUBNET}" "${WG_SPOKE}")"

  echo "Deployment summary:"
  echo "Profile: ${HUB_PROFILE}"
  echo "Spoke slot: ${WG_SPOKE}"
  echo "Spoke tunnel address: ${spoke_tunnel_ip}/32"
  echo "Hub endpoint: ${HUB_ENDPOINT}:${hub_port}"
  echo "Hub tunnel address: ${hub_tunnel_ip}/32"
  echo "Persistent keepalive: ${PERSISTENT_KEEPALIVE}"
  echo "WireGuard config: /etc/wireguard/wg0.conf"
  echo "Spoke public key: ${SPOKE_PUBLIC_KEY}"
  echo "Spoke private key file: ${SPOKE_PRIVATE_KEY_FILE}"
  echo "Spoke public key file: ${SPOKE_PUBLIC_KEY_FILE}"
  echo "Remote SSH user for HUB access: ${HUB_REMOTE_SSH_USER}"

  if [[ "${PRESEED_REMOVED}" == "true" ]]; then
    echo "ConsolePi preseed file: removed after successful install"
  elif [[ "${INSTALL_CONSOLEPI}" == "true" ]]; then
    echo "ConsolePi preseed file: ${CONSOLEPI_PRESEED_FILE}"
    if [[ "${KEEP_PRESEED}" == "true" ]]; then
      echo "ConsolePi preseed retention: enabled by --keep-preseed"
    fi
  fi

  echo "Deployed public key file: /etc/wireguard/wg0.publickey"
  echo "Rendered summary: ${SCRIPT_DIR}/rendered/summary.txt"
  echo "ConsolePi API check: curl -s http://127.0.0.1:5000/api/v1.0/details | head"
  echo "ConsolePi mode: API-only (mDNS disabled)"
  echo
  echo "Next check: ${SUDO} wg show"
  print_runtime_status
}

print_runtime_status() {
  local wg_output

  echo
  echo "Runtime status:"

  if wg_output="$(wg show wg0 2>&1)"; then
    echo "  tunnel status: up (wg0 active)"
    echo "  wg show wg0:"
    while IFS= read -r line; do
      echo "    ${line}"
    done <<< "${wg_output}"
  else
    echo "  tunnel status: down (wg0 not active)"
    echo "  wg show wg0 error: ${wg_output}"
  fi

  if command -v systemctl >/dev/null 2>&1; then
    if systemctl is-active --quiet consolepi-api; then
      if command -v curl >/dev/null 2>&1 && curl -fsS --max-time 3 http://127.0.0.1:5000/api/v1.0/details >/dev/null 2>&1; then
        echo "  API status:    up (consolepi-api active and reachable)"
      elif command -v wget >/dev/null 2>&1 && wget -q -T 3 -O - http://127.0.0.1:5000/api/v1.0/details >/dev/null 2>&1; then
        echo "  API status:    up (consolepi-api active and reachable)"
      else
        echo "  API status:    down (service active but endpoint unreachable)"
      fi
    else
      echo "  API status:    down (consolepi-api service inactive)"
    fi
  else
    echo "  API status:    unknown (systemctl not available)"
  fi
}

usage() {
  cat <<EOF
Usage: ./deploy-spoke.sh [options]

Options:
  --new-key       Force generation of a new spoke private key
  --get-key       Print the current spoke public key and exit
  --render-config Render spoke config from .env only (no install/apply)
  --status        Print live tunnel/API status and exit
  --keep-preseed  Keep ConsolePi preseed file after install
  --help          Show this help
EOF
}

for arg in "$@"; do
  case "$arg" in
    --new-key)
      NEW_KEY_REQUESTED="true"
      ;;
    --get-key)
      GET_KEY_REQUESTED="true"
      ;;
    --render-config)
      RENDER_CONFIG_ONLY="true"
      ;;
    --status)
      STATUS_ONLY="true"
      ;;
    --keep-preseed)
      KEEP_PRESEED="true"
      ;;
    --help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: ${arg}" >&2
      usage >&2
      exit 1
      ;;
  esac
done

SUDO=""

download_repo_file() {
  local repo_path="$1"
  local target_path="$2"
  local url="${RAW_BASE}/${repo_path}"

  mkdir -p "$(dirname "${target_path}")"
  if command -v curl >/dev/null 2>&1; then
    curl -fsSL "${url}" -o "${target_path}"
  elif command -v wget >/dev/null 2>&1; then
    wget -q "${url}" -O "${target_path}"
  else
    echo "Need curl or wget to pull missing files from ${REPO_URL}." >&2
    return 1
  fi
}

ensure_repo_asset() {
  local local_path="$1"
  local repo_path="$2"

  if [[ ! -f "${local_path}" ]]; then
    echo "Missing ${local_path}; pulling ${repo_path} from ${REPO_URL}@${REPO_REF}"
    download_repo_file "${repo_path}" "${local_path}"
  fi
}

render_config_from_env() {
  load_env_file || return 1

  local wg_profile
  local wg_subnet
  local wg_spoke
  local hub_port
  local hub_tunnel_ip
  local spoke_tunnel_ip
  local spoke_profile_label
  local spoke_private_key

  wg_profile="${HUB_PROFILE:-}"
  wg_subnet="${WG_SUBNET:-}"
  wg_spoke="${WG_SPOKE:-}"
  spoke_private_key="${SPOKE_PRIVATE_KEY:-}"

  : "${wg_profile:?HUB_PROFILE must be set}"
  : "${wg_subnet:?WG_SUBNET must be set}"
  : "${wg_spoke:?WG_SPOKE must be set}"
  : "${HUB_ENDPOINT:?HUB_ENDPOINT must be set}"
  : "${HUB_PUBLIC_KEY:?HUB_PUBLIC_KEY must be set}"
  PERSISTENT_KEEPALIVE="${PERSISTENT_KEEPALIVE:-25}"

  if is_placeholder_value "${spoke_private_key}" "CHANGE_ME_SPOKE_PRIVATE_KEY"; then
    spoke_private_key="$(resolve_private_key_from_state 2>/dev/null || true)"
  fi

  if [[ -z "${spoke_private_key}" ]]; then
    echo "No spoke private key available. Run full deploy to generate it, or use --new-key." >&2
    return 1
  fi

  if is_placeholder_value "${HUB_PUBLIC_KEY}" "CHANGE_ME_HUB_PUBLIC_KEY"; then
    echo "HUB_PUBLIC_KEY must be set to a real HUB public key." >&2
    return 1
  fi

  case "${wg_profile}" in
    trusted|untrusted)
      ;;
    *)
      echo "HUB_PROFILE must be 'trusted' or 'untrusted'" >&2
      return 1
      ;;
  esac

  hub_port="$(derive_hub_port_from_profile "${wg_profile}")"
  hub_tunnel_ip="$(derive_hub_ip_from_subnet "${wg_subnet}")"
  spoke_tunnel_ip="$(derive_spoke_ip_from_subnet "${wg_subnet}" "${wg_spoke}")"
  spoke_profile_label="$(printf '%s' "${wg_profile}" | tr '[:lower:]' '[:upper:]')"

  mkdir -p "${SCRIPT_DIR}/profiles" "${SCRIPT_DIR}/rendered"

  cat > "${SCRIPT_DIR}/profiles/wg0.conf.example" <<EOF
# ${spoke_profile_label} spoke template

[Interface]
Address = ${spoke_tunnel_ip}/32
PrivateKey = ${spoke_private_key}

[Peer]
PublicKey = ${HUB_PUBLIC_KEY}
Endpoint = ${HUB_ENDPOINT}:${hub_port}
AllowedIPs = ${hub_tunnel_ip}/32
PersistentKeepalive = ${PERSISTENT_KEEPALIVE}
EOF

  cp "${SCRIPT_DIR}/profiles/wg0.conf.example" "${SCRIPT_DIR}/rendered/wg0.conf"

  cat > "${SCRIPT_DIR}/rendered/summary.txt" <<EOF
  Rendered spoke profile: ${wg_profile}
  WG subnet: ${wg_subnet}
  Spoke slot: ${wg_spoke}
  Spoke address: ${spoke_tunnel_ip}/32
  Hub endpoint: ${HUB_ENDPOINT}:${hub_port}
  AllowedIPs: ${hub_tunnel_ip}/32
Output config: ${SCRIPT_DIR}/rendered/wg0.conf
EOF

    echo "Rendered ${wg_profile} spoke config at ${SCRIPT_DIR}/rendered/wg0.conf"
}

prompt_required() {
  local label="$1"
  local default_value="${2:-}"
  local reply

  while true; do
    if [[ -n "${default_value}" ]]; then
      read -r -p "${label} [${default_value}]: " reply
      reply="${reply:-${default_value}}"
    else
      read -r -p "${label}: " reply
    fi

    if [[ -n "${reply}" ]]; then
      printf '%s\n' "${reply}"
      return 0
    fi

    echo "A value is required."
  done
}

validate_port() {
  local port="$1"

  [[ "${port}" =~ ^[0-9]+$ ]] || return 1
  ((port >= 1 && port <= 65535))
}

prompt_port() {
  local label="$1"
  local default_value="$2"
  local reply

  while true; do
    reply="$(prompt_required "${label}" "${default_value}")"
    if validate_port "${reply}"; then
      printf '%s' "${reply}"
      return 0
    fi
    echo "Enter a valid port number."
  done
}

install_consolepi() {
  local installer="/tmp/ConsolePi-install-${TIMESTAMP}.sh"
  local system_timezone
  local system_hostname
  local country_code
  local locale_code

  system_timezone="$(timedatectl show -p Timezone --value 2>/dev/null || true)"
  system_timezone="${system_timezone:-UTC}"
  system_hostname="$(hostname -s 2>/dev/null || hostname 2>/dev/null || echo consolepi)"
  country_code="$(resolve_country_code)"
  locale_code="${country_code,,}"

  mkdir -p "${CONSOLEPI_PRESEED_DIR}"
  cat > "${CONSOLEPI_PRESEED_FILE}" <<EOF
hostname=${system_hostname}
tz=${system_timezone}
wlan_country=${country_code}
locale=${locale_code}
auto_launch=true
no_users=true
no_ipv6=true
do_blue=false
doapt=true
dopip=true
EOF
printf 'consolepi_pass=%q\n' "${CONSOLEPI_PASSWORD}" >> "${CONSOLEPI_PRESEED_FILE}"

  if command -v wget >/dev/null 2>&1; then
    wget -q https://raw.githubusercontent.com/Pack3tL0ss/ConsolePi/master/installer/install.sh -O "${installer}"
  else
    ${SUDO} apt-get update
    ${SUDO} apt-get install -y curl
    curl -fsSL https://raw.githubusercontent.com/Pack3tL0ss/ConsolePi/master/installer/install.sh -o "${installer}"
  fi

  ${SUDO} bash "${installer}" -C "${CONSOLEPI_PRESEED_FILE}" --silent -p "${CONSOLEPI_PASSWORD}"
  rm -f "${installer}"
}

systemd_unit_exists() {
  local unit_name="$1"
  systemctl list-unit-files --type=service --no-legend 2>/dev/null | awk '{print $1}' | grep -qx "${unit_name}"
}

configure_consolepi_api_only_mode() {
  if ! command -v systemctl >/dev/null 2>&1; then
    echo "Skipping ConsolePi service management: systemctl not available."
    return 0
  fi

  local api_unit="consolepi-api.service"
  local mdns_units=("consolepi-mdnsreg.service" "consolepi-mdnsbrowse.service")
  local unit

  # API must be reachable by the HUB to populate remote adapters.
  if systemd_unit_exists "${api_unit}"; then
    ${SUDO} systemctl enable --now consolepi-api >/dev/null 2>&1 || true
    echo "ConsolePi API service enabled."
  else
    echo "ConsolePi API service not found; skipping API enable."
  fi

  # API-only mode: disable mDNS advertise/browse services.
  for unit in "${mdns_units[@]}"; do
    if systemd_unit_exists "${unit}"; then
      ${SUDO} systemctl disable --now "${unit%.service}" >/dev/null 2>&1 || true
    fi
  done
  echo "ConsolePi mDNS services disabled (if present)."
}

harden_consolepi_account() {
  local nologin_shell=""

  if ! id consolepi >/dev/null 2>&1; then
    return 0
  fi

  if command -v passwd >/dev/null 2>&1; then
    ${SUDO} passwd -l consolepi >/dev/null 2>&1 || true
  fi

  nologin_shell="$(command -v nologin 2>/dev/null || true)"
  if [[ -n "${nologin_shell}" ]]; then
    ${SUDO} usermod -s "${nologin_shell}" consolepi >/dev/null 2>&1 || true
  fi

  echo "ConsolePi account hardened: password locked${nologin_shell:+, shell set to nologin}."
}

echo "ConnectPi spoke installer"
echo

ensure_repo_asset "${SCRIPT_DIR}/.env.example" "SPOKE/.env.example"

if [[ "${GET_KEY_REQUESTED}" == "true" ]]; then
  print_current_spoke_public_key
  exit 0
fi

if [[ "${RENDER_CONFIG_ONLY}" == "true" ]]; then
  render_config_from_env
  exit 0
fi

if [[ "${STATUS_ONLY}" == "true" ]]; then
  print_runtime_status
  exit 0
fi

if [[ ${EUID} -ne 0 ]]; then
  if command -v sudo >/dev/null 2>&1; then
    SUDO="sudo"
  else
    echo "Run as root or install sudo." >&2
    exit 1
  fi
fi

load_env_file_if_present

if [[ -z "${HUB_PROFILE:-}" ]]; then
  while true; do
    HUB_PROFILE="$(prompt_required "HUB profile (trusted/untrusted)" "untrusted")"
    case "${HUB_PROFILE}" in
      trusted|untrusted)
        break
        ;;
      *)
        echo "HUB_PROFILE must be trusted or untrusted."
        ;;
    esac
  done
fi

if [[ -z "${WG_SUBNET:-}" ]]; then
  if [[ "${HUB_PROFILE}" == "trusted" ]]; then
    WG_SUBNET="$(prompt_required "WireGuard subnet for this profile" "10.99.99.0/24")"
  else
    WG_SUBNET="$(prompt_required "WireGuard subnet for this profile" "10.99.98.0/24")"
  fi
fi

if [[ -z "${WG_SPOKE:-}" ]]; then
  WG_SPOKE="$(prompt_port "Spoke slot index" "1")"
fi

if [[ -z "${HUB_ENDPOINT:-}" ]]; then
  HUB_ENDPOINT="$(prompt_required "Hub endpoint hostname or public IP" "change-me.example.com")"
fi

if is_placeholder_value "${HUB_PUBLIC_KEY:-}" "CHANGE_ME_HUB_PUBLIC_KEY"; then
  HUB_PUBLIC_KEY="$(prompt_required "Hub public key")"
fi

PERSISTENT_KEEPALIVE="${PERSISTENT_KEEPALIVE:-25}"

INSTALL_CONSOLEPI="${INSTALL_CONSOLEPI:-true}"

if bool_is_true "${INSTALL_CONSOLEPI}"; then
  INSTALL_CONSOLEPI="true"
else
  INSTALL_CONSOLEPI="false"
fi

if is_placeholder_value "${HUB_PUBLIC_KEY}" "CHANGE_ME_HUB_PUBLIC_KEY"; then
  echo "HUB_PUBLIC_KEY must be set to a real HUB public key in ${ENV_FILE}." >&2
  exit 1
fi

if [[ -z "${HUB_REMOTE_SSH_USER}" ]]; then
  HUB_REMOTE_SSH_USER="$(prompt_required "Remote SSH user that HUB should use" "$(resolve_default_remote_ssh_user)")"
fi

while true; do
  if [[ -z "${HUB_REMOTE_SSH_PUBKEY}" ]]; then
    HUB_REMOTE_SSH_PUBKEY="$(prompt_required "HUB remote SSH public key (from HUB consolepi/ssh/hub_spoke_ed25519.pub)")"
  fi

  if is_valid_ssh_public_key "${HUB_REMOTE_SSH_PUBKEY}"; then
    break
  fi

  echo "Invalid SSH public key format. Paste a full key line such as ssh-ed25519 AAAA..."
  HUB_REMOTE_SSH_PUBKEY=""
done

${SUDO} apt-get update
${SUDO} apt-get install -y wireguard

if [[ "${NEW_KEY_REQUESTED}" == "true" ]] || is_placeholder_value "${SPOKE_PRIVATE_KEY:-}" "CHANGE_ME_SPOKE_PRIVATE_KEY"; then
  SPOKE_PRIVATE_KEY="$(generate_spoke_private_key)"
  echo "Generated spoke private key."
fi

SPOKE_PUBLIC_KEY="$(derive_public_key_from_private_key "${SPOKE_PRIVATE_KEY}")"

if [[ "${INSTALL_CONSOLEPI}" == "true" ]]; then
  CONSOLEPI_PASSWORD="$(od -An -N16 -tx1 /dev/urandom | tr -d ' \n')"
fi

mkdir -p "${SCRIPT_DIR}/rendered"
SPOKE_PRIVATE_KEY_FILE="${SCRIPT_DIR}/rendered/spoke.privatekey"
SPOKE_PUBLIC_KEY_FILE="${SCRIPT_DIR}/rendered/spoke.publickey"
printf '%s\n' "${SPOKE_PRIVATE_KEY}" > "${SPOKE_PRIVATE_KEY_FILE}"
printf '%s\n' "${SPOKE_PUBLIC_KEY}" > "${SPOKE_PUBLIC_KEY_FILE}"
chmod 600 "${SPOKE_PRIVATE_KEY_FILE}" "${SPOKE_PUBLIC_KEY_FILE}"

if [[ "${NEW_KEY_REQUESTED}" == "true" ]]; then
  echo "Rotated spoke keypair via --new-key."
  echo "Spoke public key: ${SPOKE_PUBLIC_KEY}"
  echo "Store this on the HUB for the matching peer slot."
fi

persist_env_file

render_config_from_env

${SUDO} mkdir -p /etc/wireguard
if [[ -f /etc/wireguard/wg0.conf ]]; then
  ${SUDO} cp /etc/wireguard/wg0.conf "/etc/wireguard/wg0.conf.bak.${TIMESTAMP}"
fi
${SUDO} cp "${SCRIPT_DIR}/rendered/wg0.conf" /etc/wireguard/wg0.conf
${SUDO} cp "${SPOKE_PRIVATE_KEY_FILE}" /etc/wireguard/wg0.privatekey
${SUDO} cp "${SPOKE_PUBLIC_KEY_FILE}" /etc/wireguard/wg0.publickey
${SUDO} chmod 600 /etc/wireguard/wg0.conf
${SUDO} chmod 600 /etc/wireguard/wg0.privatekey /etc/wireguard/wg0.publickey

${SUDO} systemctl enable wg-quick@wg0
if ${SUDO} systemctl is-active --quiet wg-quick@wg0; then
  ${SUDO} systemctl restart wg-quick@wg0
else
  ${SUDO} systemctl start wg-quick@wg0
fi

if [[ "${INSTALL_CONSOLEPI}" == "true" ]]; then
  install_consolepi
  # Preseed contains a password; remove it after a successful install unless requested otherwise.
  if [[ "${KEEP_PRESEED}" != "true" ]] && [[ -f "${CONSOLEPI_PRESEED_FILE}" ]]; then
    rm -f "${CONSOLEPI_PRESEED_FILE}"
    PRESEED_REMOVED="true"
  fi
fi

configure_consolepi_api_only_mode
harden_consolepi_account
ensure_hub_remote_ssh_access "${HUB_REMOTE_SSH_USER}" "${HUB_REMOTE_SSH_PUBKEY}"

echo
echo "Install complete."
print_deployment_summary